on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main

name: SonarQube Scan Static
jobs:

  ejecutar_sonar:

    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@main
    - name: pintando coverage
      run: cat coverage.xml
    - name: cambiando directorio
      working-directory: ./
      run: ls
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.0.1
      env:
        SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
